@startuml
package "es.fempa.acd.plataformacursosonline" {
    class PlataformacursosonlineApplication

    package config {
        class SecurityConfig
    }

    package controller {
        class AuthController
        class CursosController
        class HomeController
        class PublicacionesController
        class RegistroController
        class UsuarioController
    }

    package model {
        class Curso
        class Publicacion
        class Rol
        class Usuario
    }

    package repository {
        class CursoRepository
        class PublicacionRepository
        class UsuarioRepository
    }

    package service {
        class CursoService
        class CustomUserDetailsService
        class PublicacionService
        class UsuarioService
    }
}

PlataformacursosonlineApplication --> SecurityConfig
PlataformacursosonlineApplication --> AuthController
PlataformacursosonlineApplication --> CursosController
PlataformacursosonlineApplication --> HomeController
PlataformacursosonlineApplication --> PublicacionesController
PlataformacursosonlineApplication --> RegistroController
PlataformacursosonlineApplication --> UsuarioController

CursosController --> CursoService
PublicacionesController --> PublicacionService
UsuarioController --> UsuarioService
HomeController --> UsuarioService

CursoService --> CursoRepository
PublicacionService --> PublicacionRepository
UsuarioService --> UsuarioRepository

Curso --> Usuario : "relación"
Publicacion --> Usuario : "escrito por"
Rol --> Usuario : "pertenece a"
@enduml
